# Generated by Django 4.1.4 on 2023-05-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfUpload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='document',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='candidate_docs',
            field=models.FileField(default='', upload_to='pdfs/Candidate_Documents'),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='source_docs',
            field=models.FileField(null=True, upload_to='pdfs/Source_Documents'),
        ),
    ]
