# Generated by Django 4.1.4 on 2023-05-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfUpload', '0002_remove_pdfdocument_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='candidate_docs',
        ),
        migrations.RemoveField(
            model_name='pdfdocument',
            name='source_docs',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='document',
            field=models.FileField(default='', upload_to='pdfs/'),
        ),
    ]
