# Generated by Django 4.1.4 on 2023-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfUpload', '0003_remove_pdfdocument_candidate_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='document',
            field=models.FileField(default='', null=True, upload_to='pdfs/'),
        ),
    ]
