# Generated by Django 4.1.4 on 2023-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfUpload', '0004_alter_pdfdocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='document',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
