# Generated by Django 4.1.4 on 2023-05-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfUpload', '0005_alter_pdfdocument_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='candidate_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='source_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
